export const data =[
    {
        id:1,
        image:"https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg",
        title:"moon"
    },
    {
        id:2,
        image:"https://res.cloudinary.com/dtpgi0zck/image/upload/s--pVmnbd1F--/c_fill,h_260,w_380/v1/EducationHub/photos/sun-blasts-a-m66-flare.jpg",
        title:"sun"
    },
    {
        id:3,
        image:"https://i.natgeofe.com/n/e484088d-3334-4ab6-9b75-623f7b8505c9/1086_4x3.jpg",
        title:"galaxy"
    },
    {
        id:4,
        image:"https://img.freepik.com/free-vector/watercolor-galaxy-background_79603-2384.jpg?w=2000",
        title:"space"
    }
]